In [1]:
print(1+1)